/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voedselbank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;

/**
 *
 * @author Niek van der Starre
 */
public class HulpverlenerWijzigen extends javax.swing.JFrame {

    private Hulpverlener hulpverlener;
    private Connection connection;
    private JFrame opener;
    private final DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");

    /**
     * Creates new form HulpverlenerWijzigen
     */
    public HulpverlenerWijzigen() {
        initComponents();
    }

    public HulpverlenerWijzigen(Hulpverlener hulpverlener) {
        this.hulpverlener = hulpverlener;
        initComponents();
        vulVelden();
    }

    public void setOpener(JFrame jf) {
        opener = jf;
        opener.setVisible(false);
    }

    /**
     * Vult de velden met informatie van de cliënt.
     */
    private void vulVelden() {
        naamVeld.setText(hulpverlener.getNaam());
        telefoonnummerVeld.setText(hulpverlener.getTelefoonnummer());
        geboortedatumVeld.setDate(hulpverlener.getGeboortedatum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        naamVeld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefoonnummerVeld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        verwijderKnop = new javax.swing.JButton();
        wijzigKnop = new javax.swing.JButton();
        geboortedatumVeld = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naam");

        naamVeld.setDocument(new TextfieldLimit(75));

        jLabel2.setText("Geboortedatum");

        telefoonnummerVeld.setDocument(new TextfieldLimit(15));

        jLabel3.setText("Telefoonnummer");

        verwijderKnop.setText("Verwijderen");
        verwijderKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderKnopActionPerformed(evt);
            }
        });

        wijzigKnop.setText("Wijzigen");
        wijzigKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wijzigKnopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(naamVeld)
                    .addComponent(telefoonnummerVeld)
                    .addComponent(verwijderKnop, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(wijzigKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geboortedatumVeld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naamVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geboortedatumVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoonnummerVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(wijzigKnop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verwijderKnop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wijzigKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wijzigKnopActionPerformed
        try {
            connection = SimpleDataSourceV2.getConnection();
            PreparedStatement ps = connection.prepareStatement("UPDATE Hulpverlener SET naam = ?, geboortedatum = ?, telefoonnummer = ? WHERE ID_hulpverlener = ?");

            ps.setString(1, naamVeld.getText());
            ps.setString(2, dateFormat.format(geboortedatumVeld.getDate()));
            ps.setString(3, telefoonnummerVeld.getText());
            ps.setInt(4, hulpverlener.getHulverlener_ID());

            ps.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_wijzigKnopActionPerformed

    private void verwijderKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderKnopActionPerformed
        try {
            connection = SimpleDataSourceV2.getConnection();
            PreparedStatement ps = connection.prepareStatement("DELETE FROM Hulpverlener WHERE ID_hulpverlener = ?");

            ps.setInt(1, hulpverlener.getHulverlener_ID());

            ps.executeUpdate();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_verwijderKnopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser geboortedatumVeld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField naamVeld;
    private javax.swing.JTextField telefoonnummerVeld;
    private javax.swing.JButton verwijderKnop;
    private javax.swing.JButton wijzigKnop;
    // End of variables declaration//GEN-END:variables
}
