/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voedselbank;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Dave
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
        setOptions();
    }

    private void setOptions() {
        setTitle("Voedselbank Haaglanden");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {

                SimpleDataSourceV2.closeConnection();
                System.out.println("De database is succesvol afgesloten");
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        clienttoevoegenKnop = new javax.swing.JButton();
        clientwijzigenKnop = new javax.swing.JButton();
        uitgiftepunttoevoegenKnop = new javax.swing.JButton();
        uitgiftepuntwijzigenKnop = new javax.swing.JButton();
        overzichtenKnop = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBestandKnop = new javax.swing.JMenu();
        importeerKnop = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienttoevoegenKnop.setText("Cliënt toevoegen");
        clienttoevoegenKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienttoevoegenKnopActionPerformed(evt);
            }
        });

        clientwijzigenKnop.setText("Cliënt wijzigen");
        clientwijzigenKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientwijzigenKnopActionPerformed(evt);
            }
        });

        uitgiftepunttoevoegenKnop.setText("Uitgiftepunt toevoegen");

        uitgiftepuntwijzigenKnop.setText("Uitgiftepunt wijzigen");

        overzichtenKnop.setText("Overzichten");
        overzichtenKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overzichtenKnopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clienttoevoegenKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientwijzigenKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uitgiftepunttoevoegenKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uitgiftepuntwijzigenKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overzichtenKnop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienttoevoegenKnop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientwijzigenKnop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uitgiftepunttoevoegenKnop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uitgiftepuntwijzigenKnop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overzichtenKnop)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        menuBestandKnop.setText("Bestand");

        importeerKnop.setText("Importeer uit Excel");
        importeerKnop.setToolTipText("Importeer overzichten uit een excel bestand naar de database");
        importeerKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeerKnopActionPerformed(evt);
            }
        });
        menuBestandKnop.add(importeerKnop);

        jMenuItem1.setText("Exporteer naar PDF");
        jMenuItem1.setToolTipText("Exporteer de geselecteerde overzichten naar een PDF bestand");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuBestandKnop.add(jMenuItem1);

        jMenuBar1.add(menuBestandKnop);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void importeerKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeerKnopActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ExcelFilter());
        fileChooser.showOpenDialog(this);

    }//GEN-LAST:event_importeerKnopActionPerformed

    private void clientwijzigenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientwijzigenKnopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientwijzigenKnopActionPerformed

    private void clienttoevoegenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienttoevoegenKnopActionPerformed
        ClientAanmaken a = new ClientAanmaken();
        a.setVisible(true);
    }//GEN-LAST:event_clienttoevoegenKnopActionPerformed

    private void overzichtenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overzichtenKnopActionPerformed
        OverzichtScherm s = new OverzichtScherm();
        s.setVisible(true);
    }//GEN-LAST:event_overzichtenKnopActionPerformed

    public static void main(String[] args) {
        MainFrame f = new MainFrame();
        f.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienttoevoegenKnop;
    private javax.swing.JButton clientwijzigenKnop;
    private javax.swing.JMenuItem importeerKnop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuBestandKnop;
    private javax.swing.JButton overzichtenKnop;
    private javax.swing.JButton uitgiftepunttoevoegenKnop;
    private javax.swing.JButton uitgiftepuntwijzigenKnop;
    // End of variables declaration//GEN-END:variables

    class ExcelFilter extends FileFilter {

        @Override
        public boolean accept(File f) {
            return false;
        }

        @Override
        public String getDescription() {
            return "All Excel files (.xlsx)";
        }

    }
}
